### ISSUE TITLE
0.2.5 causes compilation errors when upgrading from 0.2.4

### ISSUE THREAD

**Issue by jakerr** [nvksv/maybe-async-cfg#11]
See: https://github.com/rust-embedded-community/ssd1306/pull/218

I realize as a `0.y.z` version there's no guarantee of stability but was the break intentional?

I noticed also that the commit (https://github.com/nvksv/maybe-async-cfg/commit/532a1587c951cd63b8718e7f59a951b0ab482e64) that updates the version to 0.2.5 also deletes all of the tests and examples from this project.
Was that intentional?
